### ISSUE TITLE
Stream Deck Plus, new events API

### ISSUE THREAD

**Issue by lunixbochs** [streamduck-org/elgato-streamdeck#1]
👋 these are breaking changes so I didn't want to just PR without reaching out.

You should check out the changes in https://github.com/lunixbochs/elgato-streamdeck and think about how to upstream. I added support for the Stream Deck Plus and took this opportunity to make the base API report a list of rich events rather than just a list of button states, as the Plus has dials and a touch screen.

**Comment by TheJebForge** [comment]
Sorry, entirely didn't notice this and instead implemented Plus support based on a nodejs library. But I guess this is already done

**Comment by TheJebForge** [comment]
Looking at this, there's 2 more events that can happen with the touch screen - long touch and swipe

**Comment by lunixbochs** [comment]
I just rebased and made PRs for a couple of my more minor changes.

I still like my edge triggered events, so I reimplemented those on top of current main again. That's just on https://github.com/lunixbochs/elgato-streamdeck and not PR'd.

**Comment by TheJebForge** [comment]
I actually just seem to not have implemented reader thing for sync version of the device. My idea is that you can receive output from Stream Deck with how it sent it if you want, or you can get a reader and get state changes instead
