### ISSUE TITLE
Update image on button press

### ISSUE THREAD

**Issue by raoulb** [streamduck-org/elgato-streamdeck#11]
How can I update an image on press of a button (or any state change for that matter)?

My approach is getting state changes with a `reader` as shown in the example.

The `get_reader(self: &Arc<Self>)` requires the `StreamDeck` device struct to be inside an Arc
to get me an `Arc<DeviceStateReader>` which I can use to call `read` on.

The problem now is: `set_button_image(&mut self, ...)` wants a mutable `StreamDeck`
which I afaics can not get (after I put the device inside an Arc).

So, I'm not sure how to combine/interleave the state change reading and image updating.

(Ideally I want to listen for events in a dedicated thread while pushing image updates to the device from the main thread.)

**Comment by TheJebForge** [comment]
`set_button_image` wasn't mutable before, but now that `StreamDeck` struct has `updated` bool, it doesn't really make sense anymore... I think that bool could be atomic instead, I will look into this when I have some free time

**Comment by raoulb** [comment]
With this limitation the crate seems to be unusable to really drive the Streamdeck hardware for non-trivial use cases. :-/

**Comment by ejiektpobehuk** [comment]
I've tried an active polling workaround with a device thread that blocks on reading a device for a bit and reads signals from another threads that want to write to the device. There is a delay caused by the reading block but it works.
