### ISSUE TITLE
Stream Deck Serial Number Sometimes including \u0001

### ISSUE THREAD

**Issue by Percy-Ikana** [streamduck-org/elgato-streamdeck#12]
Seemingly at random, typically switching on reboots, the serial number for my stream deck XL will either include \u0001, or not include it. 

AsyncStreamDeck.serial_number().await.unwrap()

**Comment by ninjadev64** [comment]
This is currently Percy-Ikana's fix for this issue in OpenDeck

https://github.com/ninjadev64/OpenDeck/blob/a2bb38b64529f2e0db258f76db748c3975c68884/src-tauri/src/devices/elgato.rs#L45

**Comment by TheJebForge** [comment]
I guess I'll just include similar fix here, since I'm not sure why the device would do that. Also I don't own XL, so I can't figure it out myself
