### ISSUE TITLE
AKP not matching the PID and Vendor ID 

### ISSUE THREAD

**Issue by d-kja** [streamduck-org/elgato-streamdeck#13]
I was testing my AKP and it wasn't working at all, so I did a little bit of research and I managed to grab the device PID and Vendor ID manually. After changing the PID/VID it worked fine. 

I'm not an expert when it comes to this kind of thing and I'm not sure if it's specific to my device, but I hope this can help.

PID/VID
```
HidDeviceInfo {
    vendor_id: 768,
    product_id: 4112,
}
```

I had to add the following lines to my rules file
```
SUBSYSTEM=="usb", ATTR{idVendor}=="0300", ATTR{idProduct}=="1010", MODE="0660", GROUP="plugdev", TAG+="uaccess"

SUBSYSTEM=="usb", ATTRS{idVendor}=="0300", ATTRS{idProduct}=="1010", MODE="0660", GROUP="plugdev", TAG+="uaccess"

KERNEL=="hidraw*", SUBSYSTEM=="hidraw", ATTR{idVendor}=="0300", ATTR{idProduct}=="1010", MODE="0660", GROUP="plugdev", TAG+="uaccess"

KERNEL=="hidraw*", SUBSYSTEM=="hidraw", ATTRS{idVendor}=="0300", ATTRS{idProduct}=="1010", MODE="0660", GROUP="plugdev", TAG+="uaccess"
```

And change the AKP PID/VID inside the code
```rs
/// Vendor ID of Ajazz Stream Deck
pub const AJAZZ_VENDOR_ID: u16 = 0x0300;

/// Product ID of Ajazz Stream Deck AK153
pub const PID_AJAZZ_AKP153: u16 = 0x1010;
```

Other than that, I had some issues with the rules file and to fix them I had to add the following tag `TAG+="uaccess"` at end of each line, and after doing that I had to run the following to apply the changes `sudo udevadm trigger` as the `sudo udevadm control --reload-rules` wasn't doing the job

**Comment by d-kja** [comment]
Also, I made the changes [here](https://github.com/d-kja/deck) if that helps with anything

**Comment by d-kja** [comment]
And correct me if I'm wrong, I've never used Streamdeck libs or anything like that, but I feel like the control over what X or Y does should be on the user's end and not the lib, so I find [this](https://github.com/streamduck-org/elgato-streamdeck/commit/8c3c9f693c16f7dfbf60e64a39d88153766daa26#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759L238) condition to be a bit weird, but like I said I don't know the whole idea

**Comment by TheJebForge** [comment]
I don't own the device, so I'm not exactly sure what it's doing there whenever you try to read data. And also you might have a different revision or just a different manufacturer for the device, is probably why the IDs don't match..

@ZCube added support to AKP, so it would be cool if they could compare their device with yours to see how they are different

**Comment by d-kja** [comment]
I also thought that it could be because I bought mine when it was just releasing, so it might be an older version. But yea that'd be a good idea, if he's up to it I'm also willing to help.

**Comment by czyz** [comment]
I bought a device that looks just like the AKP153 from aliexpress for $50. It has a Vendor ID of 0x5548 and a Product ID of 0x6670 (not 0x6674). The device is emblazoned "FHOOU" on the front, and says "MiraBox HSV293S" on the sticker on the back of the panel. I think this could be just another AKP153, it looks just like the white variant, other than the FHOOU branding. When I figure out how to Rust, I'll see if I can't test a connection to it after changing the Product ID in the code or adding the device.

**Comment by d-kja** [comment]
it's pretty simple to test, just go to my branch and copy what I did, just change the PID and VID with the ones that you found and you should be good to go

**Comment by GodinRaider** [comment]
Is it possible to also add support for the AKP153R version?
VID_0300&PID_1020

**Comment by teras** [comment]
sure but before that, did you follow the recommendations of d-kja? Especially if [this](https://github.com/streamduck-org/elgato-streamdeck/issues/13#issuecomment-2267174135) was required for you.

Also did you run the simple app to test that keyboard up and down event is thrown?

**Comment by ninjadev64** [comment]
> sure but before that, did you follow the recommendations of d-kja? Especially if [this](https://github.com/streamduck-org/elgato-streamdeck/issues/13#issuecomment-2267174135) was required for you.
> 
> Also did you run the simple app to test that keyboard up and down event is thrown?

I guided them to do that on Discord, this was the result of changing the PIDs/VIDs and running the sample.

```
Compiling elgato-streamdeck v0.7.1 (C:\Users\Godin\AppData\Local\OpenDeck\elgato-streamdeck)
   Compiling simple v0.0.0 (C:\Users\Godin\AppData\Local\OpenDeck\elgato-streamdeck\examples\simple)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 1.55s
     Running `target\debug\simple.exe`
Akp153 3257D40E374D 4128
thread 'main' panicked at src/main.rs:20:124:
called `Result::unwrap()` on an `Err` value: HidError(HidApiError { message: "Get Input/Feature Report DeviceIoControl: (0x00000001) Неверная функция." })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\simple.exe` (exit code: 101)
```

**Comment by teras** [comment]
then maybe the devices are not compatible? since we are talking about low level stuff, if the buffer is not correct memory corruption might happen. Luckily the Akp153 and Akp153E seems to be "compatible" to each other. Only the ID changes.

**Comment by teras** [comment]
You mean to see the input/output from the USB right? I totally agree, otherwise we're blind.

**Comment by d-kja** [comment]
yea, he'd have to compare that with the code on this repo to see what's actually happening

**Comment by teras** [comment]
@GodinRaider I decided to plunge deep and I tried to perform USB monitoring myself, to see what happens with my device, to see if I found anything that could help you identify the problem. Although it wasn't the easiest thing, it is something doable. 

You need to install [WIreshark](https://wiki.wireshark.org/CaptureSetup/USB), using [USBPcap](https://desowin.org/usbpcap/) as a plugin (you just put some files in a folder). Of course everything has to be done in Windoww on a machine that already runs the Ajazz software: that's what it does all the work. Then you monitor only `in` and `out` packages. You'll know that they are the correct ones, since on the description there will be a HID section. That HID section is the important one. Compare this with [Zcubes' notes](https://gist.github.com/ZCube/430fab6039899eaa0e18367f60d36b3c), see what's different Start with a clean, blank window, otherwise it will refresh like mad and make you crazy. Press a button, see the `in` command. Send one picture (just one!) see the commands.

If you gather all this information then the protocol is there and it will help you understand what's wrong and it crashes. Just find what your system has different from the documented one.

**Comment by d-kja** [comment]
welp PR merged, closing this issue

**Comment by czyz** [comment]
> it's pretty simple to test, just go to my branch and copy what I did, just change the PID and VID with the ones that you found and you should be good to go

Thanks. I've made a branch of elgato-streamdeck and added my device's PID and VID to all relevant places in the files, and it works. I've made a pull request against the main branch, with any luck it'll get merged.
