### ISSUE TITLE
Incorrect rotation/flip on Mini

### ISSUE THREAD

**Issue by tbmatuka** [streamduck-org/elgato-streamdeck#14]
Key images on my Mini are rotated off by 180 degrees. Switching the flip from Y to X or rotation from 90 to 270 solves it. I'm not sure if that's the correct config for all Minis (especially Mk2). Has the library been tested/used with a Mini before?

**Comment by ninjadev64** [comment]
Another issue from OpenDeck, sorry @TheJebForge :smiling_face_with_tear:

**Comment by TheJebForge** [comment]
I only own Original V2 and Plus, a lot of code was taken from different similar libs. I will address this (and most other issues here) tomorrow

**Comment by ninjadev64** [comment]
> I only own Original V2 and Plus, a lot of code was taken from different similar libs. I will address this (and most other issues here) tomorrow

Thanks.

By the way, another user with a Stream Deck Mini has confirmed this today.
