### ISSUE TITLE
Unable to locate my device Streamdeck Mini on Arch Linux using OpenDeck

### ISSUE THREAD

**Issue by teras** [streamduck-org/elgato-streamdeck#16]
This is a [followup issue](https://github.com/ninjadev64/OpenDeck/issues/24), after finding out that maybe the problem is on the upstream library, instead of OpenDeck.

The problem is that my StreamDeck device is not shown at all. I have installed all the udev rules and actually the python-based applications understand my device and works as expected. Unfortunately OpenDeck doesn't recognize it.

After some long discussions with the author of OpenDeck @ninjadev64 , it was proposed that the problem is not on the app itself but probably on the upstream library and to try to run the upstream sample myself.

I tried to run the [sample app](https://github.com/streamduck-org/elgato-streamdeck/tree/main/examples/simple), where I had to make a minor change to make it work in Cargo.toml: `hidapi = { version = "2.6", default-features = false, features=["linux-static-libusb"] }`

Then, after `cargo run` the application, I found that nothing gets displayed. 
I know nothing about rust, but I can put some printfs here and there. So I found that the code before [`for (kind, serial) in list_devices(&hid) {`](https://github.com/streamduck-org/elgato-streamdeck/blob/06c78324c2a3eec82cc19caa7c1b1fcc4bf3457a/examples/simple/src/main.rs#L14) is executed but it doesn't enter the for loop. It looks like the `list_devices` returns an empty list?

Thank you for your time

**EDIT**
I forgot to mention that my device's serial number is `Invalid SN! ` (note there's a space after the `!`). I have contacted Elgato support but up to now couldn't help on how to fix this or even if its fixable (I am still in touch with them but it takes ages to talk with them).

I also [see here](https://github.com/streamduck-org/elgato-streamdeck/blob/06c78324c2a3eec82cc19caa7c1b1fcc4bf3457a/src/lib.rs#L68) that there's a break out of loop if the SN doesn't look proper, like what happens to my case. Maybe this is the reason?

**Comment by teras** [comment]
I just did. The sample app works perfectly after this patch. I can't tell about OpenDeck since I had issues building it, but as I said, the device works fine with python-based applications, despite having this odd and unusual SN.

https://github.com/streamduck-org/elgato-streamdeck/pull/17

**Comment by teras** [comment]
According to Elgato, this is not a firmware issue, but maybe a hardware issue. They proposed me to send back the device to them to fix is. Given these circumstances, it might be  a non issue to remove the check of the valid serian number, but on the other hand, if checking doesn't provide any real benefit (and IMHO it doesn't) maybe the check indeed should be removed, since I might not be the only one with this issue and there's no reason to cut out users for a non required check.

**Comment by ninjadev64** [comment]
You also mentioned that the Python library is functional with your device, which confirms the checks are unnecessary.

**Comment by teras** [comment]
That is correct. [The python-based](https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/issues/112) works flawlessly. Even the Windows (official) app works without any problem. In both (Python and Windows) the issue is cosmetic only.

**Comment by TheJebForge** [comment]
Sorry for the delay, been away doing work and personal stuff (also I forgor). Will merge the change
