### ISSUE TITLE
Should set_button_image take a borrowed image?

### ISSUE THREAD

**Issue by londospark** [streamduck-org/elgato-streamdeck#3]
Hi,

I'm using set_button_image a lot to show when a button is toggled or to register a press and seem to have to clone the DynamicImages that I use a lot. Could they be borrowed instead to avoid the high number of clones?

**Comment by TheJebForge** [comment]
If you're doing a lot of set_button_image, consider using convert_image util function to convert DynamicImage into DeviceImage and then using write_button_image that also works much faster than set since it doesn't need to convert images

**Comment by londospark** [comment]
Thank you - I will look into that

**Comment by TheJebForge** [comment]
set_button_image takes owned DynamicImage because it needs to convert the image first before it can be sent to the device

**Comment by TheJebForge** [comment]
Err, meant write_image and just byte buffers instead of DeviceImage, forgot that I deleted that and just used byte buffers

**Comment by londospark** [comment]
Thank you - I'm trying it now and at the moment I'm having to `Box::leak(Box::new())` the images that I'm converting, is that expected or am I misusing something.

Once again, thank you for your very fast and helpful responses

**Comment by TheJebForge** [comment]
You should just keep the byte buffer around somewhere..
```rust
let bytes: Vec<u8> = convert_image(device.kind(), dynamic_image).unwrap(); // Handle the error if you can
// You can then store the bytes where ever..

// When you want to set the image to the stream deck, first argument is the index of the button you want to set the image to
device.write_image(0, &bytes).unwrap(); // Handle the error since the device could have been disconnected
```

**Comment by TheJebForge** [comment]
You can also check the source of set_button_image because this is what it does..
```rust 
/// Sets specified button's image
pub fn set_button_image(&self, key: u8, image: DynamicImage) -> Result<(), StreamDeckError> {
    let image_data = convert_image(self.kind, image)?;
    Ok(self.write_image(key, &image_data)?)
}
```

**Comment by londospark** [comment]
Ahhh, that's interesting - it works well with the sync version. I was using the async one and the code is slightly different there. Thank you. Might move back to that one at some point if I need it

**Comment by TheJebForge** [comment]
I actually forgot if it works properly in async one.. I'll check it

**Comment by TheJebForge** [comment]
Async version is indeed broken in that sense, it's expecting a static reference while you can't really provide that.. might need to instead have the write_image accept Arcs or something

**Comment by londospark** [comment]
Thank you, would you like me to close this and add that as an issue?

**Comment by TheJebForge** [comment]
I will just quickly push out an update, already done changing the things, but here's the code that worked for me

https://gist.github.com/TheJebForge/d352a70a4350fcbfb46528e837d82748

**Comment by TheJebForge** [comment]
https://docs.rs/elgato-streamdeck/latest/elgato_streamdeck/asynchronous/struct.AsyncStreamDeck.html#method.write_image

**Comment by TheJebForge** [comment]
Cloning Arcs should be fine I think

**Comment by londospark** [comment]
Thank you - cloning Arcs is pretty much free IMHO, it just points to the same memory.
