### ISSUE TITLE
Elgato Stream deck Neo support ?

### ISSUE THREAD

**Issue by AkechiShiro** [streamduck-org/elgato-streamdeck#7]
Hello, is this currently supported ? https://github.com/Julusian/node-elgato-stream-deck/issues/87 ?

I think not at least according to the description, I can help do some testing if needed and maybe also try and contribute to a PR if I can find enough time.

**Comment by TheJebForge** [comment]
Currently not, will have to look for some free time to look into it

**Comment by AkechiShiro** [comment]
Do you have the device can I help in any way, how would I get started ?

**Comment by AkechiShiro** [comment]
I have started to modify a few files notably `info.rs` but I can't compile the project to test it, could you let me know how can I do some testing ?

**Comment by ejiektpobehuk** [comment]
I'm getting familiar with this project and might try to implement neo support in the next couple of days.
I don't have the device but I can find all the necessary things in `node-elgato-stream-deck`.

@AkechiShiro Do you have the Stream Deck Neo device?
After implementing the change I can walk you through building and running it on NixOS.

**Comment by AkechiShiro** [comment]
Yes I do own one @ejiektpobehuk

**Comment by AkechiShiro** [comment]
I've started working on it, I'll push the code in a draft PR @ejiektpobehuk

**Comment by AkechiShiro** [comment]
see #9 @ejiektpobehuk

**Comment by ejiektpobehuk** [comment]
fyi, I've started working on the neo support.

Neo has a new way of user input. Elgato calls it "touch points", Julusian calls it "touch buttons".
For now I'm going with points because it's easier to distinguish from keys and is original terminology. At least it is on the web page of neo.

Haven't gotten to the point led stripes yet.

**Comment by AkechiShiro** [comment]
Thanks for the update @ejiektpobehuk, will you be able to complete the WIP PR I pushed #9 ?

**Comment by AkechiShiro** [comment]
Will require a new release for the lib so that upstream can have the support as well @TheJebForge

**Comment by AkechiShiro** [comment]
Is there the need to add a new udev rule for this deck as well ? @TheJebForge
